version: '3' 
services:
  python-docker:
    image: hajerbouani/python-docker:1.2
    ports: 
      - 8000:8000
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
volumes:
  mongo-data: 
    driver: local

